-- MySQL Script generated by MySQL Workbench
-- Tue Nov  7 17:04:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consultas` (
  `idConsultas` INT NOT NULL,
  `Nombre de consulta` VARCHAR(45) NULL,
  `Recibos_idRecibos` INT NOT NULL,
  `Pagos_idPagos` INT NOT NULL,
  `Facturas_idFacturas` INT NOT NULL,
  `Inventario_idProducto` INT NOT NULL,
  `Pagos Personal_idPagos Personal` INT NOT NULL,
  PRIMARY KEY (`idConsultas`),
  CONSTRAINT `fk_Consultas_Recibos1`
    FOREIGN KEY (`Recibos_idRecibos`)
    REFERENCES `mydb`.`Recibos` (`idRecibos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consultas_Pagos1`
    FOREIGN KEY (`Pagos_idPagos`)
    REFERENCES `mydb`.`Pagos` (`idPagos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consultas_Facturas1`
    FOREIGN KEY (`Facturas_idFacturas`)
    REFERENCES `mydb`.`Facturas` (`idFacturas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consultas_Inventario1`
    FOREIGN KEY (`Inventario_idProducto`)
    REFERENCES `mydb`.`Inventario` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consultas_Pagos Personal1`
    FOREIGN KEY (`Pagos Personal_idPagos Personal`)
    REFERENCES `mydb`.`Pagos Personal` (`idPagos Personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Consultas_Recibos1_idx` ON `mydb`.`Consultas` (`Recibos_idRecibos` ASC) VISIBLE;

CREATE INDEX `fk_Consultas_Pagos1_idx` ON `mydb`.`Consultas` (`Pagos_idPagos` ASC) VISIBLE;

CREATE INDEX `fk_Consultas_Facturas1_idx` ON `mydb`.`Consultas` (`Facturas_idFacturas` ASC) VISIBLE;

CREATE INDEX `fk_Consultas_Inventario1_idx` ON `mydb`.`Consultas` (`Inventario_idProducto` ASC) VISIBLE;

CREATE INDEX `fk_Consultas_Pagos Personal1_idx` ON `mydb`.`Consultas` (`Pagos Personal_idPagos Personal` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Facturas` (
  `idFacturas` INT NOT NULL,
  `Valor a pagar` FLOAT NOT NULL,
  `Fecha de pago` DATE NOT NULL,
  PRIMARY KEY (`idFacturas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventario` (
  `idProducto` INT NOT NULL,
  `Nombre del producto` VARCHAR(45) NOT NULL,
  `Fecha de ingreso` VARCHAR(45) NOT NULL,
  `Valor` FLOAT NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Recibos_idRecibos` INT NULL,
  PRIMARY KEY (`idProducto`),
  CONSTRAINT `fk_Inventario_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_Recibos1`
    FOREIGN KEY (`Recibos_idRecibos`)
    REFERENCES `mydb`.`Recibos` (`idRecibos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Inventario_Usuario_idx` ON `mydb`.`Inventario` (`Usuario_idUsuario` ASC) VISIBLE;

CREATE INDEX `fk_Inventario_Recibos1_idx` ON `mydb`.`Inventario` (`Recibos_idRecibos` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagos` (
  `idPagos` INT NOT NULL,
  `Fecha` VARCHAR(45) NULL,
  `Pagos Personal_idPagos Personal` INT NOT NULL,
  `Facturas_idFacturas` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPagos`),
  CONSTRAINT `fk_Pagos_Pagos Personal1`
    FOREIGN KEY (`Pagos Personal_idPagos Personal`)
    REFERENCES `mydb`.`Pagos Personal` (`idPagos Personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagos_Facturas1`
    FOREIGN KEY (`Facturas_idFacturas`)
    REFERENCES `mydb`.`Facturas` (`idFacturas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagos_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pagos_Pagos Personal1_idx` ON `mydb`.`Pagos` (`Pagos Personal_idPagos Personal` ASC) VISIBLE;

CREATE INDEX `fk_Pagos_Facturas1_idx` ON `mydb`.`Pagos` (`Facturas_idFacturas` ASC) VISIBLE;

CREATE INDEX `fk_Pagos_Usuario1_idx` ON `mydb`.`Pagos` (`Usuario_idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Pagos Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagos Personal` (
  `idPagos Personal` INT NOT NULL,
  `Nombre empleado` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Numero de cedula` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NULL,
  `Fecha de pago` DATE NULL,
  PRIMARY KEY (`idPagos Personal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recibos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recibos` (
  `idRecibos` INT NOT NULL,
  `Fecha de recibo` DATE NULL,
  `Valor` FLOAT NULL,
  `Nombre del comprador` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Garantía` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idRecibos`),
  CONSTRAINT `fk_Recibos_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Recibos_Usuario1_idx` ON `mydb`.`Recibos` (`Usuario_idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Numero de telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
